### ISSUE TITLE
Casting Error when starting the graph view.

### ISSUE THREAD

**Issue by thunter1000** [Flaredown/FlaredownAndroid#67]
Casting error... occurred when starting the graph web view.

```
10-09 10:58:07.351 20092-20092/com.flaredown.flaredownApp.DEBUG E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.flaredown.flaredownApp.DEBUG, PID: 20092
  java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.flaredown.flaredownApp.DEBUG/com.flaredown.flaredownApp.Checkin.CheckinFragment}: java.lang.ClassCastException: com.flaredown.flaredownApp.Checkin.CheckinFragment cannot be cast to android.app.Activity
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2548)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
      at android.app.ActivityThread.-wrap12(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6077)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
   Caused by: java.lang.ClassCastException: com.flaredown.flaredownApp.Checkin.CheckinFragment cannot be cast to android.app.Activity
      at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2538)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:6077) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

Line numbers should be correct to this commit: 1c78c09219cf9aaf4090bf7e236895f36128109c

**Comment by thunter1000** [comment]
The actual issue is to do with the web view trying to launch the check in activity. This is because of the fragment refactor and the web view activity trying to start a fragment not an activity.

MainActivity now accepts an intent extra to load the correct view at launch.
